export default {
    products: [ 
        {
        _id:'1',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'2',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'3',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'4',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'5',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'6',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'7',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'8',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'9',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'10',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'11',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id:'12',
        name: 'fourth Street',
        category: 'wine',
        image: '/images/4th-Street-Red.jpeg',
        price: 999,
        brand: 'nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    }
]
};